# Simple GitLab CI for Heroku PHP deployment
stages:
  - deploy

deploy_to_heroku:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to Heroku via Git..."
    - git push git@heroku.com:staff-helper.git HEAD:main
  only:
    - main
  when: manual
